### ISSUE TITLE
Ubuntu イメージのダウンロードができない

### ISSUE THREAD

**Issue by YazawaKenichi** [CIT-Autonomous-Robot-Lab/raspicat_documentation#69]
[このページ](https://uhobeike.github.io/raspicat_documentation/document/real_machine/set_up/wired/) にある、[ここをクリックするとダウンロードが始まります] をクリックしてもダウンロードが始まりません

**Comment by YazawaKenichi** [comment]
最初のコメントに

> このページ にある

とありますが、ドキュメント自体の URL が変更されました

新しいドキュメント自体の URL は[こちら](https://cit-autonomous-robot-lab.github.io/raspicat_documentation/document/real_machine/set_up/wired/) です

ドキュメント自体の URL は変更されましたが、相変わらず `[ここをクリックするとダウンロードが始まります]` をクリックすると `404 Not Found` が表示されています

**Comment by uhobeike** [comment]
* #92
で対応
